In [3]:
import numpy as np
import pandas as pd

In [6]:
#1. 
# Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно
a = np.linspace(12, 23, 12, dtype=int)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [75]:
#2. 
Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.
print(a.reshape(12,1), '\n')
print(a.reshape(6,2), '\n')
print(a.reshape(4,3), '\n')
print(a.reshape(3,4), '\n')
print(a.reshape(2,6), '\n')

ValueError: cannot reshape array of size 10 into shape (12,1)

In [22]:
# 3. 
# Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 
#(в трех примерах - для обозначения числа столбцов, в двух - для строк).
print(a.reshape(-1,1), '\n')
print(a.reshape(-1,2), '\n')
print(a.reshape(4,-1), '\n')
print(a.reshape(3,-1), '\n')
print(a.reshape(2,-1), '\n')

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]] 

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]] 

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]] 

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]] 



In [66]:
# 4. 
# Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

# Нельзя, поскольку такой массив имеет номер столбца и строки
b = a.reshape(-1,1)
b[1][0]

18

In [49]:
# 5. 
# Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со 
# средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же 
# атрибутом size, как и исходный массив.
a = np.random.normal(size = (3, 4))
print(a)
a.flatten()

[[-1.11469801 -1.82923867  1.58154316 -1.56328479]
 [-1.30951564 -0.20065724  0.129347    1.07309587]
 [ 0.23450538 -0.37847074  0.3830375  -0.17775377]]


array([-1.11469801, -1.82923867,  1.58154316, -1.56328479, -1.30951564,
       -0.20065724,  0.129347  ,  1.07309587,  0.23450538, -0.37847074,
        0.3830375 , -0.17775377])

In [60]:
# 6.
#Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [77]:
# 7.
#Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2.
#В чем разница между массивами a и b?
b = np.arange(20, 0, -2).reshape(1,-1)
print(b)
print(b[0][2])
# Ответ тот же, что и в 4 вопросе: у массива b есть номер столбца и строки, а у массива a есть только номер строки. Кроме того,
# у массива b две скобки, то есть это двумерный массив.

[[20 18 16 14 12 10  8  6  4  2]]
16


In [85]:
# 8.Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, 
# чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.
a = np.zeros((2, 2))
b = np.ones((3, 2))
print(a, '\n')
print(b, '\n')
print(np.vstack((a, b)), '\n')
print('Size is: ', np.vstack((a, b)).size)

[[0. 0.]
 [0. 0.]] 

[[1. 1.]
 [1. 1.]
 [1. 1.]] 

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 

10


In [104]:
# 9.
# Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, 
# чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем 
# транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер 
# имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

a = np.arange(0, 12)
A = a.reshape(4, 3)
print(a)
At = A.T
B = A@At
print(B)
print(B.shape)
print("Определитель: ", np.linalg.det(B), "\nРанг: ", np.linalg.matrix_rank(B))

# Обратную матрицу получить не удастся, т.к. в матрице есть линейно зависимые строки (ранг 2 из 4), 
# поэтому матрица B является вырожденной

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
(4, 4)
Определитель:  0.0 
Ранг:  2


In [ ]:
# 10.
# Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.
np.random.seed(42)

In [ ]:
# 11.
# Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел 
# от 0 до 16 невключительно. 

In [172]:
c = np.random.randint(0, 16, 16)
c

array([ 4,  6, 15,  3, 13,  6,  5,  9,  3,  8, 14, 13,  8,  6, 11,  0])

In [179]:
# 12.
# Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из 
# предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.
C = c.reshape(4, 4)
print(C)
D = C*10 + B
D_inv = np.linalg.inv(D)
print("Определитель: ", np.linalg.det(D), "\nРанг: ", np.linalg.matrix_rank(D), 
      "\nОбратная матрица: \n", D_inv)

[[ 4  6 15  3]
 [13  6  5  9]
 [ 3  8 14 13]
 [ 8  6 11  0]]
Определитель:  -13775600.000000061 
Ранг:  4 
Обратная матрица: 
 [[ 0.04970963  0.03322686  0.0306934  -0.06828886]
 [-0.25416824 -0.13652835 -0.19664624  0.37071344]
 [ 0.08623218  0.0399518   0.06107756 -0.11491623]
 [ 0.04279596  0.02735852  0.04200325 -0.07224658]]


In [ ]:
# 13.
# Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались 
# только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве 
# источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv 
# равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент 
# матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [188]:
D_inv = np.where(D_inv > 0, 1, 0)
print(D_inv, '\n')
E = np.where(D_inv == 0, C, B)
print(E)

[[1 1 1 0]
 [0 0 0 1]
 [1 1 1 0]
 [1 1 1 0]] 

[[  5  14  23   3]
 [ 13   6   5 122]
 [ 23  86 149  13]
 [ 32 122 212   0]]
